import friedrice from './Images/friedrice.jpeg';
import riceEfo from './Images/yoruba/riceandEfo.jpeg';
import BreadandAkara from './Images/yoruba/bread and akara.jpeg';
import Amalaewedu from './Images/yoruba/Amala Ewedu and gbegiri.jpeg';
import Bitterleafsoup from './Images/yoruba/Bitter leaf soup.jpeg';
import EfoElegusi from './Images/yoruba/Efo Elegusi.jpeg';
import fufu from './Images/yoruba/Fufu with Goat Meat Soup.jpeg';
import Gari from './Images/yoruba/Garri.jpeg';
import Goatmeat from './Images/yoruba/Goat Meat Pepper Soup With Boiled Plantain.jpeg';
import moimoi from './Images/yoruba/Moimoi.jpeg';
import ofadaRicae from './Images/yoruba/Ofada Stew and Rice.jpeg';
import Okro from './Images/yoruba/okrosoup.jpeg';
import Rice from './Images/yoruba/riceandEfo.jpeg';
import Yamegg from './Images/yoruba/Yam and Egg.jpeg';
import stew from './Images/yoruba/Yoruba Stew.jpeg';
import Abacha from './Images/igbo/Abacha.jpeg';
import Abachandi from './Images/igbo/Abacha ndi Enugu.jpeg';
import Njamafufu from './Images/igbo/Njama Njama and FuFu.jpeg';
import ohasoup from './Images/igbo/Oha soup.jpeg';
import yamubga from './Images/igbo/Yam and ugba _ukpaka sauce.jpeg';
import chickenveg from './Images/chicken with vegetable.jpeg';
import Miyan from './Images/Hausa/Miyan Taushe.jpeg';
import Dashishi from './Images/Hausa/Dashishi.jpeg';
import GroundnutSoup from './Images/Hausa/Groundnut Soup (Miyan Geda) _ Hausa Foods and Recipe.jpeg';
import Hausaricecakes from './Images/Hausa/Masa (Hausa rice cakes).jpeg';
import Masa from './Images/Hausa/Waina Recipe - Masa- Hausa Dish - Afrolems Nigerian Food Blog.jpeg';
import BeefSuya from './Images/Hausa/Nigerian Beef Suya - Chef Lola Kitchen.jpeg';
import DanWake from './Images/Hausa/Dan Wake _ Hausa Delicious Food Recipes.jpeg';

export const tablesdes = [
    {id: 1, name: 'Bread and Akara', img: BreadandAkara, alt: 'BreadandAkara', 
    ingredient: 'The ingredients for bread include four cups of all-purpose flour, two tablespoons of sugar, one tablespoon of salt, two teaspoons of instant yeast, one and a half cups of warm water, and two tablespoons of vegetable oil or melted butter. For Akara, the ingredients consist of two cups of black-eyed peas or brown beans, one medium onion, one to two green chilies, salt to taste, water for blending, and vegetable oil for frying.'},
    
    {id: 2, name: 'Oha Soup', img: ohasoup, alt: 'Oha Soup',
        ingredient: 'The ingredients for Oha soup include one pound of Oha leaves, one pound of assorted meats (such as beef, goat, or chicken), and one cup of palm oil. Additionally, you will need one to two tablespoons of ground crayfish, one to two tablespoons of ground pepper, salt to taste, and one cup of cocoyam paste or ground egusi for thickening. These ingredients combine to create a rich and flavorful traditional Nigerian dish.'},
    
    {id: 3, name: 'Fried Rice', img: friedrice, alt: 'Fried Rice',
        ingredient: 'The ingredients for fried rice include three cups of long-grain rice, one cup of mixed vegetables (such as peas, carrots, and bell peppers), one medium onion (chopped), and two to three cloves of garlic (minced). For seasoning, you will need two to three tablespoons of soy sauce, one to two teaspoons of curry powder, and salt to taste. You can also add one cup of cooked shrimp, chicken, or beef for protein, along with two to three tablespoons of vegetable oil for frying. These ingredients combine to create a flavorful and colorful fried rice dish.'},
    
    {id: 4, name: 'Rice and Vegetable', img: riceEfo, alt: 'Rice and Efo', 
    ingredient: 'To prepare rice and efo, you will need two cups of long-grain rice and 200 grams of African spinach (efo) or other leafy greens. The sauce requires 200 grams of blended tomatoes, 100 grams of blended bell peppers, and one medium-sized chopped onion. For flavor, use  100 grams of palm oil, 200 grams of assorted meats (such as pomo, goat, or chicken), one Knorr cube, and salt to taste. Optionally, you can add habanero pepper for spice and ground crayfish for extra flavor. These ingredients combine to create a delicious and hearty dish.'},
    
    {id: 5, name: 'Chicken and Vegetable', img: chickenveg, alt: 'Chicken and Vegetable',
        ingredient: 'To prepare chicken and vegetables, you will need one pound of chicken, cut into pieces, and two cups of mixed vegetables such as bell peppers, carrots, and broccoli. For flavor, use two tablespoons of soy sauce, one tablespoon of olive oil, and one teaspoon of minced garlic, along with salt and pepper to taste. Optionally, add one teaspoon of ginger for extra flavor. These ingredients combine to create a delicious and healthy dish.'},
    
    {id: 6, name: 'Goat Meat', img: Goatmeat, alt: 'Goat Meat', 
        ingredient: 'To prepare a delicious goat meat dish, you will need two pounds of goat meat, cut into pieces. For flavor, include one medium onion, chopped, along with two to three cloves of minced garlic and one to two inches of minced or grated ginger. You will also need two to three tablespoons of vegetable oil or palm oil for cooking. Season the dish with two to three tablespoons of ground pepper, one to two teaspoons of salt, and one to two Knorr cubes for added depth. Optionally, fresh herbs like thyme or bay leaves can enhance the flavor. These ingredients come together to create a savory and tender goat meat dish.'},
    
    {id: 7, name: 'Ofada Rice', img: ofadaRicae, alt: 'Ofada Rice',
        ingredient: 'To prepare Ofada rice, you will need two cups of Ofada rice, which is known for its distinct flavor. For cooking, use four cups of water. The sauce requires one cup of blended green bell peppers, one cup of blended tomatoes, and one medium onion, chopped. For richness, include two to three tablespoons of palm oil, along with one to two teaspoons of ground crayfish for added flavor. Season with salt to taste and one to two seasoning cubes, such as Knorr. Optionally, you can add assorted meats or fish for protein. These ingredients come together to create a delicious and aromatic Ofada rice dish, often served with a spicy sauce.'},
    
    {id: 8, name: 'Moimoi', img: moimoi, alt: 'Moimoi', 
        ingredient: 'Moi Moi is a traditional Nigerian dish, a steamed bean pudding made from black-eyed peas or brown beans. The beans are soaked, peeled, and blended into a smooth paste, then mixed with chopped onions for flavor and fresh peppers, such as bell peppers or Scotch bonnet, for heat and color. Vegetable oil, often palm oil, adds richness and moisture, while seasoning with salt and cubes enhances the taste. Water is added to achieve the right batter consistency. Optional ingredients like diced bell peppers, boiled eggs, fish, or meat can be included for extra flavor and texture. This versatility makes Moi Moi a beloved staple in Nigerian cuisine, enjoyed on its own or as a side dish.'},
    
    {id: 9, name: 'Okro', img: Okro, alt: 'Okro', ingredient: 'Okro soup is a popular West African dish, especially in Nigeria, made primarily from fresh okra, which is sliced or blended to create a thick, mucilaginous texture. The soup often includes various proteins such as meat, fish, and sometimes snails, enhancing its flavor. Seasoning with salt, pepper, and seasoning cubes is essential, while palm oil adds richness and vibrant color. Variations may include vegetables like spinach or bitter leaf for added nutrition. Typically served with fufu, pounded yam, or rice, okro soup is a hearty and beloved meal in West African cuisine.'},
    
    {id: 10, name: 'Rice', img: Rice, alt: 'Rice', ingredient: 'Rice is a staple food enjoyed worldwide, known for its versatility and ability to complement a variety of dishes. It is typically cooked by boiling or steaming, resulting in fluffy grains that can be served plain or seasoned. In many cultures, rice is paired with meats, vegetables, or sauces, making it a key component of numerous meals. Different varieties, such as basmati, jasmine, and brown rice, offer unique flavors and textures. Rice can also be prepared in various forms, including fried rice, risotto, and rice pilaf, showcasing its adaptability in culinary traditions. Its nutritional value, providing carbohydrates and essential nutrients, makes rice a fundamental part of diets globally.'},
    
    {id: 11, name: 'Yam and Egg', img: Yamegg, alt: 'Yam and Egg', ingredient: 'Yam and egg is a simple yet satisfying dish popular in many West African countries. The dish typically features boiled or fried yam, which is starchy and hearty, providing a filling base. The yam is often cut into slices or chunks and cooked until tender. Eggs are usually prepared alongside the yam, either scrambled, fried, or boiled, adding protein and richness to the meal. The combination can be seasoned with spices, onions, and peppers to enhance the flavor. Yam and egg can be enjoyed as a breakfast option or a light meal, offering a nutritious balance of carbohydrates and protein. Its simplicity and delicious taste make it a beloved choice for many.'},
    
    {id: 12, name: 'Stew', img: stew, alt: 'Stew', ingredient: 'Stew is a hearty and flavorful dish enjoyed in various cuisines around the world. It typically consists of meat, vegetables, and a rich sauce, all simmered together to develop deep flavors. The base of a stew often includes ingredients like onions, garlic, and tomatoes, which provide a savory foundation. Meats such as beef, chicken, or lamb are commonly used, along with a variety of vegetables like carrots, potatoes, and bell peppers. Seasonings, including herbs and spices, enhance the taste and aroma of the dish. Stews can be served with rice, bread, or dumplings, making them a filling and comforting meal. Their versatility allows for countless variations, reflecting regional ingredients and culinary traditions, making stew a beloved dish across cultures.'},
    
    {id: 13, name: 'Bitterleaf Soup', img: Bitterleafsoup, alt: 'Bitterleaf Soup', ingredient: 'Bitterleaf soup, also known as Ofe Onugbu, is a traditional Nigerian dish celebrated for its rich flavor and health benefits. The soup is primarily made from fresh bitter leaves, which are known for their distinct, slightly bitter taste. The leaves are usually washed and squeezed to reduce their bitterness before being added to the soup. The base of the soup typically includes a variety of meats, such as goat, beef, or fish, along with seasonings like onions, pepper, and seasoning cubes. Palm oil is often added to give the soup a rich color and depth of flavor. Bitterleaf soup is often thickened with ground seeds, such as melon seeds (egusi) or cocoyam, which contribute to its hearty texture. It is commonly served with fufu, pounded yam, or rice, making it a nutritious and satisfying meal that showcases the unique flavors of Nigerian cuisine.'},
    
    {id: 14, name: 'Amala and Ewedu', img: Amalaewedu, alt: 'Amala and Ewedu', ingredient: 'Amala and ewedu is a traditional Nigerian dish that is both nutritious and flavorful. Amala is a type of swallow made from yam flour or cassava flour, which is cooked with water to create a smooth, stretchy consistency. It is typically served as a side dish and is known for its unique texture and ability to complement various soups. Ewedu, on the other hand, is a soup made from jute leaves, which are rich in vitamins and minerals. The leaves are cooked until tender and often blended to create a smooth consistency. Ewedu is seasoned with spices, onions, and sometimes enriched with locust beans for added flavor. Together, amala and ewedu create a delicious and satisfying meal. The smoothness of the amala pairs perfectly with the slightly viscous texture of the ewedu soup, making it a popular choice for lunch or dinner in many Nigerian households. This combination not only highlights the rich culinary traditions of Nigeria but also provides a balanced meal.'},
    
    {id: 15, name: 'Efo Elegusi', img: EfoElegusi, alt: 'Efo Elegusi', ingredient: 'Efo and egusi is a popular Nigerian dish that highlights the rich flavors of leafy greens and a savory melon seed sauce. Efo, short for Efo Riro, is a vegetable soup made primarily from spinach or other leafy greens, such as amaranth leaves. The greens are cooked with a blend of ingredients, including onions, peppers, and tomatoes, creating a vibrant and nutritious base. Egusi refers to ground melon seeds, which are used to thicken the soup and add a rich, nutty flavor. The combination of efo and egusi results in a hearty dish that is both flavorful and satisfying. The soup is typically seasoned with spices, salt, and often enriched with proteins like fish, meat, or shrimp, enhancing its taste and nutritional value. Efo and egusi is commonly served with a side of swallow, such as pounded yam or fufu, making it a beloved meal in Nigerian cuisine that showcases the use of fresh vegetables and traditional cooking methods.'},
    
    {id: 16, name: 'Fufu', img: fufu, alt: 'Fufu', ingredient: 'Fufu is a traditional staple food in many West African countries, known for its smooth, stretchy texture and versatility. It is made from starchy ingredients such as cassava, yams, or plantains, which are boiled until soft and then pounded or blended into a dough-like consistency. Fufu is typically served as an accompaniment to soups and stews, allowing it to absorb the rich flavors of the accompanying dishes. It is often enjoyed with popular soups like egusi, efo riro, or okra soup. The process of eating fufu usually involves tearing off a small piece, rolling it into a ball, and using it to scoop up the soup or stew. This dish is not only filling but also provides a good source of carbohydrates, making it a vital part of many diets in the region. Fufu unique texture and ability to complement a variety of flavors make it a beloved choice in West African cuisine.'},
    
    {id: 17, name: 'Gari', img: Gari, alt: 'Gari', ingredient: 'Gari is a popular staple food in West Africa, particularly in Nigeria, made from fermented and processed cassava tubers. The preparation involves peeling, grating, and fermenting the cassava, which is then dried and roasted to create granules. Gari has a coarse texture and a slightly sour taste due to the fermentation process. It can be enjoyed in various ways: often served as a side dish with soups and stews, or mixed with water to form a dough-like consistency known as gari soak. In this form, it is typically combined with sugar, milk, or groundnuts for a sweet snack or breakfast option. Gari is not only versatile but also rich in carbohydrates, making it a significant source of energy. Its affordability and ease of preparation contribute to its popularity as a staple food in many households across West Africa.'},
    
    {id: 18, name: 'Abacha', img: Abacha, alt: 'Abacha', ingredient: 'Abacha, also known as African salad, is a traditional dish from Nigeria, particularly among the Igbo people. It is made from fermented and dried African oil bean (also known as "fermented cassava") that is soaked in water to soften it before being mixed with various ingredients. The dish is typically prepared by combining the softened abacha with ingredients such as palm oil, onions, pepper, and sometimes ground crayfish or locust beans for added flavor. It is often garnished with sliced vegetables like ugba (oil bean), garden eggs, and sometimes fish or meat, making it a nutritious and flavorful meal. Abacha is usually served cold or at room temperature and is often enjoyed as a snack or side dish. Its unique taste and texture, along with its vibrant colors, make it a popular choice at gatherings and celebrations, showcasing the rich culinary traditions of Nigeria.'},
    
    {id: 19, name: 'Abachandi', img: Abachandi, alt: 'Abachandi', ingredient: 'Abachandi, also known as "Abacha ndi Oka," is a traditional dish from the Igbo people of Nigeria. It is a variation of the popular abacha (African salad) but incorporates additional ingredients and flavors. The dish is primarily made from fermented and dried cassava, which is soaked in water to soften it. In preparing abachandi, the softened cassava is mixed with palm oil, onions, and a variety of seasonings, including pepper and locust beans, to enhance its flavor. What sets abachandi apart is the addition of ingredients like ugba (oil bean), fish, and sometimes vegetables, which contribute to its nutritional value and taste. Abachandi is typically served as a cold dish and is often enjoyed as a snack or side dish at gatherings and celebrations. Its unique combination of flavors and textures makes it a beloved choice in Igbo cuisine, reflecting the rich culinary heritage of the region.'},
    
    {id: 20, name: 'Njama Njama and Fufu', img: Njamafufu, alt: 'Njama Njama and Fufu', ingredient: 'Njamafufu, also known as "Njamah," is a traditional dish from the Cameroonian and Central African regions. It is a type of fufu made from cassava or plantains, which are boiled and then pounded into a smooth, stretchy consistency. The dish is often served with various soups, stews, or sauces, making it a versatile accompaniment to a wide range of meals. Njamafufu is known for its ability to absorb flavors from the accompanying dishes, enhancing the overall dining experience. In some variations, njamafufu may be flavored with ingredients like palm oil or spices, adding depth to its taste. It is a staple food in many households, providing a good source of carbohydrates and energy. Its unique texture and ability to pair well with different flavors make njamafufu a cherished part of the culinary traditions in the regions where it is enjoyed.'},
    
    {id: 21, name: 'Oha Soup', img: ohasoup, alt: 'Oha Soup', ingredient: 'Oha soup, also known as Ofe Oha, is a traditional Igbo dish from Nigeria, celebrated for its rich flavor and unique ingredients. The soup is primarily made from the leaves of the Oha tree, which are known for their distinct taste and nutritional benefits. To prepare Oha soup, the leaves are typically shredded and cooked with a base of meat (such as goat, beef, or chicken) and sometimes fish. The soup is thickened with ground seeds, often using cocoyam or a combination of ground crayfish and locust beans, which adds depth and richness to the dish. Seasonings such as palm oil, onions, and spices are added to enhance the flavor. Oha soup is usually served with a side of swallow, such as pounded yam or fufu, making it a hearty and satisfying meal. Its unique combination of flavors and textures makes Oha soup a beloved dish in Igbo cuisine, often enjoyed during special occasions and gatherings.'},
    
    {id: 22, name: 'Yam and Ugba', img: yamubga, alt: 'Yam and Ugba', ingredient: 'Yam and ugba is a traditional Nigerian dish that combines boiled yam with ugba, also known as oil bean. This dish is particularly popular among the Igbo people and is often enjoyed as a side dish or a light meal. To prepare yam and ugba, the yam is peeled, cut into slices, and boiled until tender. Ugba, which is made from fermented oil beans, is typically prepared by slicing and seasoning it with ingredients such as palm oil, onions, pepper, and sometimes ground crayfish or locust beans. This mixture adds a rich, nutty flavor to the dish. Once the yam is cooked, it is served alongside the seasoned ugba, creating a delicious combination of flavors and textures.'},
    
    {id: 23, name: 'Miyan', img: Miyan, alt: 'Miyan', ingredient: 'Miyan, also known as Miyan Taushe, is a traditional Hausa soup made from pumpkin and various spices. The ingredients include one medium-sized pumpkin (or butternut squash), one cup of groundnut (peanut) paste, one medium onion (chopped), two to three cups of water, and assorted meats (such as beef or chicken). Season with salt, pepper, and spices like ginger and garlic to taste. This hearty soup is often served with rice or fufu.'},
    
    {id: 24, name: 'Dashishi', img: Dashishi, alt: 'Dashishi', ingredient: 'Dashishi is a traditional Hausa dish made from rice and beans. The ingredients include two cups of rice, one cup of black-eyed peas or brown beans, one medium onion (chopped), and spices such as salt, pepper, and ground ginger. The rice and beans are cooked together with water until tender, creating a nutritious and filling meal that is often enjoyed with a side of stew or sauce.'},
    
    {id: 25, name: 'Groundnut Soup', img: GroundnutSoup, alt: 'Groundnut Soup', ingredient: 'Groundnut soup, also known as Miyan Geda, is a rich and creamy soup made from ground peanuts. The ingredients include one cup of ground peanuts, one medium onion (chopped), two to three cups of water, assorted meats (such as chicken or beef), and spices like salt, pepper, and chili. The soup is simmered until thickened and is often served with rice or fufu, providing a delicious and satisfying meal.'},
    
    {id: 26, name: 'Hausa Rice Cakes', img: Hausaricecakes, alt: 'Hausa Rice Cakes', ingredient: 'Masa, or Hausa rice cakes, are made from a batter of fermented rice and spices. The ingredients include two cups of rice, one cup of water, one teaspoon of yeast, and salt to taste. The rice is soaked, blended into a smooth batter, and allowed to ferment for several hours. The batter is then poured into molds and cooked until golden brown, resulting in fluffy rice cakes that are often served with a spicy sauce or stew.'},
    
    {id: 27, name: 'Masa', img: Masa, alt: 'Masa', ingredient: 'Masa is a traditional Hausa dish made from fermented rice batter. The ingredients include two cups of rice, one cup of water, one teaspoon of yeast, and salt to taste. The rice is soaked, blended into a smooth batter, and allowed to ferment for several hours. The batter is then poured into molds and cooked until golden brown, resulting in fluffy rice cakes that are often served with a spicy sauce or stew.'},
    
    {id: 28, name: ' Yam and Ugba', img: yamubga, alt: 'Yam and Ugba', ingredient: 'Yam and ugba is a traditional Nigerian dish that combines boiled yam with ugba, also known as oil bean. This dish is particularly popular among the Igbo people and is often enjoyed as a side dish or a light meal. To prepare yam and ugba, the yam is peeled, cut into slices, and boiled until tender. Ugba, which is made from fermented oil beans, is typically prepared by slicing and seasoning it with ingredients such as palm oil, onions, pepper, and sometimes ground crayfish or locust beans. This mixture adds a rich, nutty flavor to the dish. Once the yam is cooked, it is served alongside the seasoned ugba, creating a delicious combination of flavors and textures.'},
    
    {id: 29, name: 'Beef Suya', img: BeefSuya, alt: 'Beef Suya', ingredient: 'Beef Suya is a popular Nigerian street food made from skewered and grilled beef. The ingredients include one pound of beef (cut into thin strips), two tablespoons of groundnut (peanut) powder, one tablespoon of cayenne pepper, one teaspoon of salt, and one tablespoon of vegetable oil. The beef is marinated with the spices and oil, then skewered and grilled until cooked through. Suya is often served with sliced onions, tomatoes, and spicy pepper sauce.'},
    
    {id: 30, name: 'Dan Wake', img: DanWake, alt: 'Dan Wake', ingredient: 'Dan Wake is a traditional Hausa dish made from a mixture of beans and flour. The ingredients include two cups of black-eyed peas or brown beans, one cup of flour (wheat or cassava), one medium onion (chopped), and salt to taste. The beans are soaked, blended, and mixed with flour and onions to form a batter. The batter is then shaped into balls and boiled until cooked. Dan Wake is often served with a spicy sauce or stew, making it a nutritious and filling meal.'}
];